name: audio_test
description: Audio demo.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  just_audio: ^0.9.31
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  file_picker: ^5.2.5
  shared_preferences: ^2.0.17
  audio_video_progress_bar: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
